name: Android Release AAB

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build AAB
        run: ./gradlew bundleRelease --stacktrace --info --warning-mode=all
        working-directory: android

      - name: Upload AAB
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY_JSON }}
          packageName: com.yourcompany.yourapp  # change this!
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: internal  # or use 'alpha', 'beta', 'production'
          status: completed
